on:
  pull_request:
    branches: [master]

name: Run Linting and Unit Tests
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click==8.0.4
          pip install black==21.12b0
          pip install flake8==3.8.3

      - name: Lint Black
        run: |
          black --check --diff --color .

      - name: Lint Flake8
        run: |
          flake8

